[package]
name = "safecast"
version = "0.1.0"
authors = ["haydnv"]
edition = "2018"
license-file = "LICENSE"
description = "Traits to define safe casting between types"
repository = "https://github.com/haydnv/safecast.git"
readme = "README"

[dependencies]
